固件升级模式:
  功能:
  参数:
  示例: '固件升级模式'
固件升级模式(忽略电量):
  功能:
  参数:
  示例: '固件升级模式(忽略电量)'
固件升级模式(授权):
  功能:
  参数:
    device_id: 设备ID码
    version: 版本号 版本0 表示不进行版本校验,用于不能降级的约束,默认0
  示例: '固件升级模式(忽略电量)',device_id=1, version=0
获得设备基本信息:
  功能:
  参数:
  示例: '获得设备基本信息'
获得设备支持的功能列表:
  功能:
  参数:
  示例: '获得设备支持的功能列表'
获得设备支持的功能列表拓展v3:
  功能:
  参数:
  示例: '获得设备支持的功能列表拓展v3'
获得设备时间:
  功能:
  参数:
  示例: '获得设备时间'
获得设备mac地址:
  功能:
  参数:
  示例: '获得设备mac地址'
获得设备电池信息:
  功能:
  参数:
  示例: '获得设备电池信息'
获得拓展功能表:
  功能:
  参数:
  示例: '获得拓展功能表'
获得设备提醒开关状态:
  功能:
  参数:
  示例: '获得设备提醒开关状态'
获得详细版本号信息:
  功能:
  参数:
  示例: '获得详细版本号信息'
获得勿扰模式参数:
  功能:
  参数:
  示例: '获得勿扰模式参数'
获取设置的卡路里/距离/中高运动时长的目标设置:
  功能:
  参数:
  示例: '获取设置的卡路里/距离/中高运动时长的目标设置'
获取走动提醒:
  功能:
  参数:
  示例: '获取走动提醒'
realme手环获取版本信息(relme定制):
  功能:
  参数:
  示例: 'realme手环获取版本信息(relme定制)'
获得实时数据(pro使用到)(gt01 pro不使用):
  功能:
  参数:
  示例: '获得实时数据(pro使用到)(gt01 pro不使用)'
获取GPS信息(GPS文件升级会用到这个)(gt01 pro不使用):
  功能:
  参数:
  示例: '获取GPS信息(GPS文件升级会用到这个)(gt01 pro不使用)'
获取gps热启动参数(GPS文件升级会用到这个)(gt01 pro不使用):
  功能:
  参数:
  示例: '获取设置的卡路里/距离/中高运动时长的目标设置'
获取gps状态(GPS文件升级会用到这个)(gt01 pro不使用):
  功能:
  参数:
  示例: '获取走动提醒'
获取运动类型(pro 老的机型使用)(gt01 pro不使用):
  功能:
  参数:
  示例: 'realme手环获取版本信息(relme定制)'
获取字库信息(pro 老的机型使用)(gt01 pro不使用):
  功能:
  参数:
  示例: '获得实时数据(pro使用到)(gt01 pro不使用)'
获取手环支持主界面排序的列表(老机型使用)(gt01 pro不使用):
  功能:
  参数:
  示例: '获取GPS信息(GPS文件升级会用到这个)(gt01 pro不使用)'
获取亮度开关:
  功能:
  参数:
  示例: '获取设置的卡路里/距离/中高运动时长的目标设置'
获取抬腕:
  功能:
  参数:
  示例: '获取走动提醒'
获取手环是否处于升级模式(阿波罗平台用得上)(gt01 pro不使用):
  功能:
  参数:
  示例: 'realme手环获取版本信息(relme定制)'
获取表盘ID(老机型使用)(gt01 pro不使用):
  功能:
  参数:
  示例: '获得实时数据(pro使用到)(gt01 pro不使用)'
获取固件日志状态:
  功能:
  参数:
  示例: '获取GPS信息(GPS文件升级会用到这个)(gt01 pro不使用)'
获取所有的健康监测开关:
  功能:
  参数:
  示例: '获取所有的健康监测开关'
文件传输配置获取:
  功能:
  参数:
    type: 运动类型 对应的图标类型 0：这个字段无效； 1：运动小图标； 2:运动大图标， 3：运动动画
    evt_type: 事件类型; 0是这个字段无效 通消息通知 比如  0x01：短信,0x02：邮件，0x03：微信 ....（上限值：0x4E20）
    sport_type: 运动类型; 0是这个字段无效 运动模式类型, 0x01 走路,0x02 跑步....
  示例: '文件传输配置获取', type=1, evt_type=0x01, sport_type=0x01
运动模式自动识别开关获取:
  功能:
  参数:
  示例: '运动模式自动识别开关获取'
获得固件三级版本和BT的3级版本:
  功能:
  参数:
  示例: '获得固件三级版本和BT的3级版本'
时间设置:
  功能:
  参数:
    year: 年
    month: 月，有效值在1~12
    day: 日 有效值：在1~31
    hour: 时，有效值在0~23
    minute: 分，有效值在0~59
    second: 秒，有效值在0~59
    week: 星期，0~6表示星期一到星期天
    utc_time: 暂时不用兼容硬件部分代码
    time_zone: 用24时区的，手机端的获取时区是整数，0-12东，13-24西
  示例: '时间设置', year=2021, month=12, day=1, hour=1, minute=1, second=1, week=1
闹钟提醒设置:
  功能:
  参数:
    id: 闹钟id号，固定（1\~最多支持闹钟个数）
    show_status:  状态：（0x55：显示， 0xAA:不显示）
    type:  类型：（0x00：起床， 0x01：睡觉， 0x02：锻炼， 0x03：吃药， 0x04：约会， 0x05：聚会， 0x06:会议， 0x07：其他）
    hour: 闹钟时（24小时制）
    minute: 闹钟分
    repetitions: 闹钟重复及开关
#      bit 0: 总开关
#      bit 1: 每周一
#      bit 2: 每周二
#      bit 3: 每周三
#      bit 4: 每周四
#      bit 5: 每周五
#      bit 6: 每周六
#      bit 7: 每周日
#      **bit位说明：**
#
#      - bit0    ：  0表示关，1表示开
#      - bit1-7: 0表示不重复，1表示重复
    snooze_duration: 贪睡时长（0表示不贪睡，0\~60，单位：分钟）
    reserved: 预留：全部补0
  示例: '闹钟提醒设置(pro 的设置用到)(gt01 pro不使用)', id=1, show_status=0x55, type=0x1, hour=1,minute=11, repetitions=2, snooze_duration=1
全天步数目标设置:
  功能:
    参数:
      type: 类型0x00:步数
      data: step_target 数值
      sleep_hour: 睡眠目标：时 预留
      sleep_minute: 睡眠目标：分 预留
    示例: '全天步数目标设置', type=0, data=2048
设置菜单列表:
  功能:
    参数:
      item_count: 个数
      item_list: 列表且自带排序
#        /*无排序情况,有值则显示,无值则不现实
#        * 有排序情况,需要按照数组从0开始依次显示
#        * 0x00 无效
#        * 0x01 步数
#        * 0x02 心率
#        * 0x03 睡眠
#        * 0x04 拍照
#        * 0x05 闹钟
#        * 0x06 音乐
#        * 0x07 秒表
#        * 0x08 计时器
#        * 0x09 运动模式
#        * 0x0A 天气
#        * 0x0B 呼吸锻炼
#        * 0x0C 查找手机
#        * 0x0D 压力
#        * 0x0E 数据三环
#        * 0x0F 时间界面
#        * 0x10 最近一次活动
#        * 0x11 健康数据
#        * 0x12 血氧
#        * 0x13 菜单设置
#        * 0x14 (20)aleax语音依次显示
    示例: '设置菜单列表', item_count=11, item_list=[1, 2,3,4,5,6,7,8,9,10,11,12,0x13]
