手环方法:
    可变: !!python/list [上滑, 下滑, 右滑, 左滑, 进入自动化指令, 点击, 短按右键, 退出自动化指令, 长亮屏, 长按, 长按右键]
    不可变: !!python/list [进入自动化指令,短按右键, 退出自动化指令, 长亮屏,长按右键]




闹钟:
  路径: !!python/list [短按右键,上滑,"点击(4,5)"] #首页进入路径
  新增闹钟: !!python/list (0, 0) #为确保按钮能够展现，做好调用一次上滑
  #操作层只有两种情况，点击、长按
  取消添加: !!python/list [0, 0]
  添加闹钟: !!python/list [0, 0]
  设置闹铃日期: !!python/list [0, 0]
  关闭闹钟: !!python/list [0, 0]
  删除闹钟: !!python/list [100, 0]
  闹钟关闭: !!python/list [0, 0]
  自定义事件:
    进入自动化: !!python/list [进入自动化指令,长亮屏]
    时钟页面: !!python/list [到功能列表时钟,时钟icon]
    闹钟页面: !!python/list [到功能列表时钟,时钟icon,闹钟icon]
    到功能列表时钟: !!python/list [短按右键,'上滑(0,320)','上滑(0,320)','上滑(0,320)','上滑(0,320)','上滑(0,320)']
    时钟icon: !!python/list ['点击(180,280)']
    闹钟icon: !!python/list ['点击(50,180)']
    秒表icon: !!python/list ['点击(150,180)']
    到表盘界面: !!python/list [短按右键]
    手表灭屏: !!python/list [进入自动化指令,灭屏,'等待5.5']
    点亮屏幕: !!python/list [短按右键]
    上滑屏幕: !!python/list ['上滑(200,200)']
    下滑屏幕: !!python/list ['下滑(200,200)']
    右滑屏幕: !!python/list ['右滑(50,150)']
    单击物理按键: !!python/list [短按右键]
    长按物理按键: !!python/list [长按右键]
    操作手表: !!python/list ['上滑(200,200)','下滑(200,200)']

运动:
  路径: !!python/list [短按右键,上滑,"点击(4,5)"] #首页进入路径
  自定义事件:
    进入自动化: !!python/list [进入自动化指令,长亮屏]
    进入运动列表: [短按右键,运动icon]
    开始运动: !!python/list [第一项运动icon]
    运动记录列表: !!python/list [短按右键,ativity,上滑,上滑,上滑]
    查看最近的一次运动记录: !!python/list [第一项运动记录icon]
    运动icon: !!python/list ["点击(100,120)"]
    第一项运动icon: !!python/list ["点击(100,50)"]
    ativity: !!python/list ["点击(100, 50)"]
    第一项运动记录icon: !!python/list ["点击(100,50)"]
    结束运动: !!python/list [短按右键,长按右键]


健康数据:
  路径: !!python/list [短按右键,上滑,"点击(4,5)"] #首页进入路径


倒计时:
   路径: !!python/list [短按右键,上滑,"点击(4,5)"] #首页进入路径




##  进入闹钟功能页面:
#  闹钟自定义: (0,0)
##  闹钟选择时间:
#  闹钟选择星期
#  闹钟选择时间确定
#  闹钟选择时间取消
#  闹钟设定确认
#  闹钟开启/关闭
#  闹钟删除



















